load pre-trained model :  /kaggle/working/pre-training/exp1_pre_attblock_fold-0_20230501_pretrained.pth
_IncompatibleKeys(missing_keys=['model.classifier.weight', 'model.classifier.bias', 'att_block.att.weight', 'att_block.att.bias', 'att_block.cla.weight', 'att_block.cla.bias'], unexpected_keys=['to_melspec_fn.spectrogram.window', 'to_melspec_fn.mel_scale.fb'])
#########################
#### Training
#### Fold: 1 | Image Size: (224, 313) | Model: tf_efficientnet_b1_ns | Batch Size: 64 | Scheduler: cos
#### Num Train: 19,627 | Num Valid: 3,381






















































































100%|██████████| 307/307 [02:56<00:00,  1.74it/s]










 96%|█████████▋| 26/27 [00:28<00:00,  1.34it/s]
100%|██████████| 27/27 [00:29<00:00,  1.09s/it]





















































































100%|██████████| 307/307 [02:54<00:00,  1.76it/s]












100%|██████████| 27/27 [00:29<00:00,  1.09s/it]
Epoch: 2 | Train Loss: 0.6908562282397614 | Val Loss: 0.6908065963674475 | Val Padded_cmAP : 0.4527998076607255





















































































100%|██████████| 307/307 [02:54<00:00,  1.76it/s]











100%|██████████| 27/27 [00:29<00:00,  1.08s/it]
Epoch: 3 | Train Loss: 0.6907034079492674 | Val Loss: 0.6907148626115587 | Val Padded_cmAP : 0.45285606370200127





















































































100%|██████████| 307/307 [02:53<00:00,  1.76it/s]












100%|██████████| 27/27 [00:29<00:00,  1.09s/it]
Epoch: 4 | Train Loss: 0.6906870659865463 | Val Loss: 0.6907127919020476 | Val Padded_cmAP : 0.45281629988882327






















































































100%|██████████| 307/307 [02:54<00:00,  1.76it/s]












100%|██████████| 27/27 [00:29<00:00,  1.10s/it]
Epoch: 5 | Train Loss: 0.6906781342208191 | Val Loss: 0.6907120744387308 | Val Padded_cmAP : 0.45281956188298444




















































































100%|██████████| 307/307 [02:53<00:00,  1.77it/s]









 96%|█████████▋| 26/27 [00:28<00:00,  1.37it/s]
100%|██████████| 27/27 [00:29<00:00,  1.09s/it]




















































































100%|██████████| 307/307 [02:53<00:00,  1.77it/s]










100%|██████████| 27/27 [00:29<00:00,  1.09s/it]
  0%|          | 0/307 [00:00<?, ?it/s]





















































































100%|██████████| 307/307 [02:53<00:00,  1.76it/s]









 93%|█████████▎| 25/27 [00:28<00:01,  1.38it/s]
100%|██████████| 27/27 [00:29<00:00,  1.10s/it]


























































 67%|██████▋   | 207/307 [01:58<00:55,  1.79it/s]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f1eac472560>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1466, in __del__
    self._shutdown_workers()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1430, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 45, in wait
    if not wait([self.sentinel], timeout):
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/opt/conda/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:
 67%|██████▋   | 207/307 [01:59<00:57,  1.74it/s]
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 152, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 138, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 405, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 170, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 127, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 395, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
